server:
  port: 3000

api:
  security:
    token:
      secret: ${JWT_SECRET:xablau}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/courselms
    username: root
    password: root
  jpa:
    show-sql: true
  security:
    user:
      name: admin
      password: admin