server:
  port: 3000

api:
  web_host: ${HOST:http://localhost}
  security:
    token:
      secret: ${JWT_SECRET:super-secret}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/courselms
    username: root
    password: root
  jpa:
    show-sql: true
  security:
    user:
      name: admin
      password: admin
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    user: ${MAIL_USER}
    password: ${MAIL_PASSWORD}

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /api-docs
